#!/bin/bash

set -e

if [ "${DEBUG}" = 1 ]; then
    set -x
fi

# Usage:
#   curl ... | ENV_VAR=... sh -
#

# info logs the given argument at info log level.
info() {
    echo "[INFO] " "$@"
}

# warn logs the given argument at warn log level.
warn() {
    echo "[WARN] " "$@" >&2
}

# fatal logs the given argument at fatal log level.
fatal() {
    echo "[ERROR] " "$@" >&2
    if [ -n "${SUFFIX}" ]; then
        echo "[ALT] Please visit 'https://github.com/rancher/rke2/releases' directly and download the latest rke2.${SUFFIX}.tar.gz" >&2
    fi
    exit 1
}

# Check variables
# INSTALL_RKE2_VERSION 과 INSTALL_RKE2_TYPE 그리고 admin 계정을 체크한다.
if [ -z ${RKE2_VERSION} ]; then
    RKE2_VERSION=v1.30.5-rc3+rke2r1
fi
if [ -z ${RKE2_TYPE} ]; then
    RKE2_TYPE=server
fi
if [ -z ${RKE2_ADMIN} ]; then
    RKE2_ADMIN=kubeops
fi

# Install Tools
info "::: Installing something ..."
apt update
# apt install iptables -y
# snap install yq jq
# apt update

# Setting up k9s
echo;echo
info "::: Install k9s tool..."
curl -sS https://webi.sh/k9s | sh
source ~/.config/envman/PATH.env
echo "source <(kubectl completion bash)" >> ~/.bashrc